[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.18"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./data/"}]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
